Repository oracle/tribuo, pull requests merged in 2022-10, with the labels that each got.

#278 Adds protobuf serialization to Tree models
  Classification/DecisionTree/src/test/java/org/tribuo/classification/dtree/TestCART.java
  Common/Trees/src/main/java/org/tribuo/common/tree/AbstractCARTTrainer.java
  Common/Trees/src/main/java/org/tribuo/common/tree/LeafNode.java
  Common/Trees/src/main/java/org/tribuo/common/tree/Node.java
  Common/Trees/src/main/java/org/tribuo/common/tree/SplitNode.java
  Common/Trees/src/main/java/org/tribuo/common/tree/TreeModel.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/LeafNodeProto.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/LeafNodeProtoOrBuilder.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/SplitNodeProto.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/SplitNodeProtoOrBuilder.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/TreeModelProto.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/TreeModelProtoOrBuilder.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/TreeNodeProto.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/TreeNodeProtoOrBuilder.java
  Common/Trees/src/main/java/org/tribuo/common/tree/protos/TribuoTree.java
  Common/Trees/src/main/resources/protos/tribuo-tree.proto
  Regression/Core/src/main/java/org/tribuo/regression/Regressor.java
  Regression/Core/src/main/java/org/tribuo/regression/protos/DimensionTupleProto.java
  Regression/Core/src/main/java/org/tribuo/regression/protos/DimensionTupleProtoOrBuilder.java
  Regression/Core/src/main/java/org/tribuo/regression/protos/TribuoRegressionCore.java
  Regression/Core/src/main/resources/protos/tribuo-regression-core.proto
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/IndependentRegressionTreeModel.java
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/protos/IndependentRegressionTreeModelProto.java
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/protos/IndependentRegressionTreeModelProtoOrBuilder.java
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/protos/TreeNodeListProto.java
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/protos/TreeNodeListProtoOrBuilder.java
  Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/protos/TribuoRegressionTree.java
  Regression/RegressionTree/src/main/resources/protos/tribuo-regression-tree.proto
  Regression/RegressionTree/src/test/java/org/tribuo/regression/rtree/TestCARTJointRegressionTrainer.java
  Regression/RegressionTree/src/test/java/org/tribuo/regression/rtree/TestCARTRegressionTrainer.java
Labels: squash-commits, OCA Verified

#254 Add classification feature selection support
  Classification/FeatureSelection/pom.xml
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/CMIM.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/DenseFSMatrix.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/FSMatrix.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/JMI.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/MIM.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/mRMR.java
  Classification/FeatureSelection/src/main/java/org/tribuo/classification/fs/package-info.java
  Classification/FeatureSelection/src/test/java/org/tribuo/classification/fs/CMIMTest.java
  Classification/FeatureSelection/src/test/java/org/tribuo/classification/fs/JMITest.java
  Classification/FeatureSelection/src/test/java/org/tribuo/classification/fs/MIMTest.java
  Classification/FeatureSelection/src/test/java/org/tribuo/classification/fs/mRMRTest.java
  Classification/pom.xml
  Core/src/main/java/org/tribuo/CategoricalInfo.java
  Core/src/main/java/org/tribuo/FeatureSelector.java
  Core/src/main/java/org/tribuo/SelectedFeatureSet.java
  Core/src/main/java/org/tribuo/dataset/SelectedFeatureDataset.java
  Core/src/main/java/org/tribuo/evaluation/EvaluationAggregator.java
  Core/src/main/java/org/tribuo/protos/ProtoUtil.java
  Core/src/main/java/org/tribuo/protos/core/FeatureSetProto.java
  Core/src/main/java/org/tribuo/protos/core/FeatureSetProtoOrBuilder.java
  Core/src/main/java/org/tribuo/protos/core/SelectedFeatureDatasetProto.java
  Core/src/main/java/org/tribuo/protos/core/SelectedFeatureDatasetProtoOrBuilder.java
  Core/src/main/java/org/tribuo/protos/core/SelectedFeatureSetProto.java
  Core/src/main/java/org/tribuo/protos/core/SelectedFeatureSetProtoOrBuilder.java
  Core/src/main/java/org/tribuo/protos/core/TribuoCore.java
  Core/src/main/java/org/tribuo/protos/core/TribuoCoreImpl.java
  Core/src/main/java/org/tribuo/provenance/FeatureSelectorProvenance.java
  Core/src/main/java/org/tribuo/provenance/FeatureSetProvenance.java
  Core/src/main/java/org/tribuo/provenance/ModelProvenance.java
  Core/src/main/java/org/tribuo/provenance/impl/FeatureSelectorProvenanceImpl.java
  Core/src/main/java/org/tribuo/transform/transformations/BinningTransformation.java
  Core/src/main/resources/protos/tribuo-core-impl.proto
  Core/src/main/resources/protos/tribuo-core.proto
  Core/src/test/java/org/tribuo/dataset/SelectedFeatureDatasetTest.java
  Core/src/test/java/org/tribuo/test/MockFeatureSelector.java
  tutorials/README.md
  tutorials/feature-selection-tribuo-v4.ipynb
Labels: squash-commits, OCA Required

#287 Fixes for test failures when running in a path with spaces in
  Classification/LibLinear/src/test/java/org/tribuo/classification/liblinear/TestLibLinearModel.java
  Classification/LibSVM/src/test/java/org/tribuo/classification/libsvm/TestLibSVM.java
  Classification/XGBoost/src/test/java/org/tribuo/classification/xgboost/TestXGBoost.java
  Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java
  Common/NearestNeighbour/src/test/java/org/tribuo/common/nearest/TestKNN.java
  Math/src/test/java/org/tribuo/math/neighbour/NeighbourQueryTestHelper.java
  Math/src/test/java/org/tribuo/math/util/SGDVectorsFromCSV.java
Labels: OCA Verified

#288 Bumping versions of XGBoost, jackson, protobuf and OCI
  Interop/OCI/pom.xml
  Json/pom.xml
  Reproducibility/pom.xml
  THIRD_PARTY_LICENSES.txt
  distribution/pom.xml
  pom.xml
Labels: OCA Verified

#290 Bumping to 5.0.0-SNAPSHOT and Java 17
  .github/workflows/maven-macos.yml
  .github/workflows/maven-ubuntu.yml
  .github/workflows/maven-windows.yml
  AnomalyDetection/Core/pom.xml
  AnomalyDetection/LibLinear/pom.xml
  AnomalyDetection/LibSVM/pom.xml
  AnomalyDetection/pom.xml
  Classification/Core/pom.xml
  Classification/DecisionTree/pom.xml
  Classification/Experiments/pom.xml
  Classification/Explanations/pom.xml
  Classification/FeatureSelection/pom.xml
  Classification/LibLinear/pom.xml
  Classification/LibSVM/pom.xml
  Classification/MultinomialNaiveBayes/pom.xml
  Classification/SGD/pom.xml
  Classification/XGBoost/pom.xml
  Classification/pom.xml
  Clustering/Core/pom.xml
  Clustering/Hdbscan/pom.xml
  Clustering/KMeans/pom.xml
  Clustering/pom.xml
  Common/LibLinear/pom.xml
  Common/LibSVM/pom.xml
  Common/NearestNeighbour/pom.xml
  Common/SGD/pom.xml
  Common/Trees/pom.xml
  Common/XGBoost/pom.xml
  Common/pom.xml
  Core/pom.xml
  Data/pom.xml
  Interop/Core/pom.xml
  Interop/ModelCard/pom.xml
  Interop/OCI/pom.xml
  Interop/ONNX/pom.xml
  Interop/Tensorflow/pom.xml
  Interop/pom.xml
  Json/pom.xml
  Math/pom.xml
  MultiLabel/Core/pom.xml
  MultiLabel/SGD/pom.xml
  MultiLabel/pom.xml
  Regression/Core/pom.xml
  Regression/LibLinear/pom.xml
  Regression/LibSVM/pom.xml
  Regression/RegressionTree/pom.xml
  Regression/SGD/pom.xml
  Regression/SLM/pom.xml
  Regression/XGBoost/pom.xml
  Regression/pom.xml
  Reproducibility/pom.xml
  Util/InformationTheory/pom.xml
  Util/ONNXExport/pom.xml
  Util/Tokenization/pom.xml
  Util/pom.xml
  distribution/pom.xml
  pom.xml
  tests/pom.xml
Labels: squash-commits, OCA Verified

#292 Add build_spec.yaml as a preparation for Oracle's GitHub repository guideline checks
  build_spec.yaml
Labels: OCA Verified

#294 Add copyright to build_spec.yaml
  build_spec.yaml
Labels: OCA Verified
